services:
  - type: web
    name: app
    env: docker
    dockerfilePath: ./Dockerfile
    port: 3010
    envVars:
      - key: POSTGRES_USER
        fromDatabase: postgres
        field: username
      - key: POSTGRES_PASSWORD
        fromDatabase: postgres
        field: password
      - key: POSTGRES_DB
        fromDatabase: postgres
        field: database
    databases:
      - name: postgres

  - type: cron
    name: prometheus
    env: docker
    dockerfilePath: ./Dockerfile.prometheus
    schedule: "@every 1m"
    command: [ "--config.file=/etc/prometheus/prometheus.yml" ]
    envVars:
      - key: POSTGRES_USER
        fromDatabase: postgres
        field: username
      - key: POSTGRES_PASSWORD
        fromDatabase: postgres
        field: password
      - key: POSTGRES_DB
        fromDatabase: postgres
        field: database

  - type: cron
    name: grafana
    env: docker
    dockerfilePath: ./Dockerfile.grafana
    schedule: "@every 1m"
    envVars:
      - key: POSTGRES_USER
        fromDatabase: postgres
        field: username
      - key: POSTGRES_PASSWORD
        fromDatabase: postgres
        field: password
      - key: POSTGRES_DB
        fromDatabase: postgres
        field: database
