services:
  - name: app
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    buildCommand: "npm run build"  
    startCommand: "node dist/main"
    envVars:
    - key: PORT
      value: 3010

  - name: prometheus
    type: web
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "--config.file=/etc/prometheus/prometheus.yml"
    envVars:
      - key: PORT
        value: 9090