services:
  - name: app
    type: web
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    buildCommand: ""  
    startCommand: ""
    envVars:
    - key: PORT
      value: 3010

  - name: prometheus
    type: web
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "--config.file=/etc/prometheus/prometheus.yml"
    envVars:
      - key: PORT
        value: 9090

  - name: grafana
    type: web
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: GF_SECURITY_ADMIN_PASSWORD
        value: ${GRAFANA_ADMIN_PASSWORD}
      - key: PORT
        value: 3000